[colors.primary]
foreground = "#c6c6c6"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#ff8389"
green = "#42be65"
yellow = "#d2a106"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#08bdba"
white = "#c6c6c6"

[colors.bright]
black = "#525252"
red = "#ffb3b8"
green = "#6fdc8c"
yellow = "#f1c21b"
blue = "#a6c8ff"
magenta = "#d4bbff"
cyan = "#3ddbd9"
white = "#ffffff"

